version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./allure-results:/app/allure-results
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
