# Generated by gRPC Python protocol compiler
import sys
import grpc

DESCRIPTOR = None

class HelloRequest:
    def __init__(self, name=""):
        self.name = name

class HelloReply:
    def __init__(self, message=""):
        self.message = message
